config/routes.rb
Rails.application.routes.draw do
  root to: 'translations#index'
  post 'translations/translate', as: :translate
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :set_defaults


  def index
  end


  def translate
    @source = translate_params[:source]
    @source_language = translate_params[:source_language]
    @destination_language = translate_params[:destination_language]
    body = {
      q: @source,
      target: @destination_language.upcase
    }
    body[:source] = @source_language.downcase unless @source_language.empty?
    translation = api_request(
      'language/translate/v2',
      method: :post,
      body: URI.encode_www_form(body)
    )
    @translation = translation['data']['translations'].first['translatedText']
    render action: :index
  end

  def translate_params
    params.permit(:source, :source_language, :destination_language)
  end

  private

  def set_defaults
    @languages = fetch_languages
  end
  def api_request(path, method: :get, body: nil)
    params = {
      headers: {
        'x-rapidapi-key': '102af2a43cmshb712411545b21b3p121e3cjsn0cc724e8fb83',
        'content-type': 'application/x-www-form-urlencoded'
      }
    }
    params[:body] = body if body
    response = Excon.send(method,
      "https://google-translate1.p.rapidapi.com/#{path}",
      params
    )
    JSON.parse(response.body)
  end
  def fetch_languages
    languages = api_request('language/translate/v2/languages')
    keys = languages['data']['languages'].map { |l| l['language'].upcase }
    I18nData
      .languages
      .slice(*keys)
      .each_with_object([]) do |(iso, name), memo|
        memo << [name, iso]
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Translate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/translations/index.html.erb
<div class="container">
  <h1 class="text-center">Translator</h1>
  <%= form_with url: translate_path, method: :post, local: true do %>
    <div class="row">
        <div class="col-lg-5">
          <div class="form-group">
            <label for="source">Translate</label>
            <%= text_area_tag :source, @source, class: 'form-control', style: 'width: 100%; height: 100px' %>
          </div>
          <div class="form-group">
            <label for="source_language">From</label>
            <%= select_tag :source_language, options_for_select(@languages, @source_language), class: 'form-control', include_blank: 'Auto-detect' %>
          </div>
        </div>
        <div class="col-lg-2 d-flex align-items-center justify-content-center">
          <button type="submit" class="btn btn-primary">
            Translate <i class="fa fa-arrow-right"></i>
          </button>
        </div>
        <div class="col-lg-5">
          <div class="form-group">
            <label for="translation">Translation</label>
            <%= text_area_tag :translation, @translation, class: 'form-control', style: 'width: 100%; height: 100px', readonly: true %>
          </div>
          <div class="form-group">
            <label for="destination_language">To</label>
            <%= select_tag :destination_language, options_for_select(@languages, @destination_language), class: 'form-control' %>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/translations/translate.html.erb
<h1>Translations#translate</h1>
<p>Find me in app/views/translations/translate.html.erb</p>